# rubocop version: 1.2.0
AllCops:
  TargetRubyVersion: 2.7.2
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Bundler/OrderedGems:
  Enabled: false
